from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT_DIR = Path(__file__).resolve().parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from src.asset_universe import asset_mapping_frame
from src.utils import resolve_path


def main() -> None:
    source = resolve_path(
        "results/tables/improved_convex_adaptive_global_relaxed_risk_parity_returns.csv"
    )
    data = pd.read_csv(source, parse_dates=["date"])
    if data.empty:
        raise ValueError(f"No portfolio rows found in {source}")

    latest = data.sort_values("date").iloc[-1]
    mapping = asset_mapping_frame().set_index("new_name")
    holding_month = (latest["date"] + pd.offsets.MonthBegin(1)).strftime("%Y-%m")
    rows: list[dict] = []
    for column in data.columns:
        if not column.startswith("weight_"):
            continue
        asset = column.removeprefix("weight_")
        weight = float(latest[column])
        if weight <= 1e-8:
            continue
        item = mapping.loc[asset]
        rows.append(
            {
                "holding_month": holding_month,
                "as_of_date": latest["date"].date().isoformat(),
                "model": "Improved Convex Adaptive Global RRP",
                "selected_candidate_id": latest["selected_candidate_id"],
                "etf": asset,
                "ticker": item["ticker"],
                "asset_class": item["asset_class"],
                "weight": weight,
                "weight_pct": weight * 100.0,
            }
        )

    holdings = pd.DataFrame(rows).sort_values(["weight", "ticker"], ascending=[False, True])
    if abs(float(holdings["weight"].sum()) - 1.0) > 1e-8:
        raise ValueError("Exported next-month holdings do not sum to 100%")
    output = resolve_path("results/tables/next_month_holdings.csv")
    holdings.to_csv(output, index=False, float_format="%.10f")
    pairs = []
    split = (len(holdings) + 1) // 2
    left = holdings.iloc[:split].reset_index(drop=True)
    right = holdings.iloc[split:].reset_index(drop=True)
    for index in range(split):
        lhs = left.iloc[index]
        if index < len(right):
            rhs = right.iloc[index]
            pairs.append(
                f"{lhs['etf']} & {lhs['ticker']} & {lhs['weight_pct']:.2f}\\% & "
                f"{rhs['etf']} & {rhs['ticker']} & {rhs['weight_pct']:.2f}\\% \\\\"
            )
        else:
            pairs.append(
                f"{lhs['etf']} & {lhs['ticker']} & {lhs['weight_pct']:.2f}\\% & --- & --- & --- \\\\"
            )
    thesis_lines = [
        "% Auto-generated by scripts/export_next_month_holdings.py",
        f"截至 {latest['date'].date().isoformat()} 的模型输出对应 {holding_month} 持仓。",
        r"\begin{table}[H]",
        r"\centering",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{3.2pt}",
        rf"\caption{{{holding_month} Improved Convex Adaptive Global RRP 持仓}}",
        r"\label{tab:next_month_holdings}",
        r"\begin{tabular}{llrllr}",
        r"\toprule",
        r"ETF & 代码 & 权重 & ETF & 代码 & 权重 \\",
        r"\midrule",
        *pairs,
        r"\bottomrule",
        r"\end{tabular}",
        r"\end{table}",
    ]
    thesis_output = resolve_path("report/thesis_latex/generated_next_month_holdings.tex")
    thesis_output.write_text("\n".join(thesis_lines) + "\n", encoding="utf-8")

    top = holdings.head(10)
    slide_lines = [
        "% Auto-generated by scripts/export_next_month_holdings.py",
        r"\scriptsize\renewcommand{\arraystretch}{1.12}",
        r"\begin{tabular}{llr}",
        r"\toprule",
        r"ETF & 代码 & 权重 \\",
        r"\midrule",
        *[f"{row.etf} & {row.ticker} & {row.weight_pct:.2f}\\% \\\\" for row in top.itertuples()],
        r"\bottomrule",
        r"\end{tabular}",
    ]
    slide_output = resolve_path("report/ppt/generated_next_month_holdings_slide.tex")
    slide_output.write_text("\n".join(slide_lines) + "\n", encoding="utf-8")
    print(f"Wrote {holding_month} holdings ({len(holdings)} positions) to {output}")


if __name__ == "__main__":
    main()
