"""Generate LaTeX snippets from authoritative CSV/Python outputs.

Outputs written to ``report/thesis_latex/``:
* ``generated_numbers.tex``       — all ``\\newcommand`` macros
* ``generated_etf_pool_table.tex``— ETF pool longtable (from asset_universe.py)
* ``generated_asset_stats_table.tex`` — ETF identity/category and descriptive stats
* ``generated_rebalance_frequency_table.tex`` — rebalance-frequency sensitivity table

Rerunning after every pipeline run keeps the thesis in sync with data.
No manual copy-paste of numbers, tickers, or statistics.
"""

from __future__ import annotations

import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

ROOT_DIR = Path(__file__).resolve().parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from src.asset_universe import ETF_UNIVERSE, AssetMapping
from src.risk_free import load_monthly_risk_free
from src.utils import get_config, resolve_path


logger = logging.getLogger("generate_thesis_numbers")

# Evaluation window — update here when the researcher extends the backtest.
_CONFIG = get_config()
_EVAL_START_DATE = _CONFIG["evaluation_start_date"]
_EVAL_END_DATE = _CONFIG["evaluation_end_date"]

# Section display names for ETF pool and stats tables.
_ASSET_CLASS_SECTION: dict[str, str] = {
    "convertible bond":          "债券类",
    "government bond":           "债券类",
    "credit bond":               "债券类",
    "money market":              "债券类",
    "china equity":              "A股宽基",
    "china equity dividend":     "A股宽基",
    "china tech equity":         "中国科技与增长",
    "china advanced manufacturing": "中国科技与增长",
    "china new energy":          "中国科技与增长",
    "china finance":             "中国行业与消费",
    "china defense":             "中国行业与消费",
    "china consumer":            "中国行业与消费",
    "hong kong equity":          "港股",
    "commodity":                 "大宗商品",
    "global equity":             "全球股票",
    "commodity equity":          "大宗商品",
}
_TICKER_SECTION_OVERRIDE: dict[str, str] = {}

# Observations below this threshold receive the $^*$ short-history marker.
_SHORT_HISTORY_OBS = 1200


# Map of model name (as it appears in the CSV) -> LaTeX command prefix.
MODEL_SLUGS: dict[str, str] = {
    "Global RRP": "global",
    "Defensive Dynamic RRP": "defensive",
    "Convex Adaptive Global RRP": "convex",
    "Improved Convex Adaptive Global RRP": "improved",
    "HRP Benchmark": "hrp",
    "HERC Benchmark": "herc",
    "Equal Weight": "equalWeight",
    "60/40 Benchmark": "sixtyForty",
}

# Map of model name -> LaTeX command prefix for sharpe-difference results.
DIFF_SLUGS: dict[tuple[str, str], str] = {
    ("Improved Convex Adaptive Global RRP", "Global RRP"): "improvedVsGlobal",
    ("Improved Convex Adaptive Global RRP", "Defensive Dynamic RRP"): "improvedVsDefensive",
    ("Improved Convex Adaptive Global RRP", "Equal Weight"): "improvedVsEqual",
    ("Global RRP", "Equal Weight"): "globalVsEqual",
    ("Defensive Dynamic RRP", "Equal Weight"): "defensiveVsEqual",
}

FREQUENCY_SLUGS: dict[str, tuple[str, str]] = {
    "W": ("freqWeekly", "周度"),
    "2W": ("freqBiweekly", "双周"),
    "M": ("freqMonthly", "月度"),
    "Q": ("freqQuarterly", "季度"),
}


def _pct(x: float, digits: int = 2) -> str:
    return f"{100.0 * x:.{digits}f}\\%"


def _num(x: float, digits: int = 3) -> str:
    return f"{x:.{digits}f}"


def _etf_section(etf: AssetMapping) -> str:
    """Return the display section name for an ETF."""
    if etf.ticker in _TICKER_SECTION_OVERRIDE:
        return _TICKER_SECTION_OVERRIDE[etf.ticker]
    return _ASSET_CLASS_SECTION.get(etf.asset_class, etf.asset_class)


def _etf_pool_table(out_dir: Path) -> None:
    """Write generated_etf_pool_table.tex — full ETF pool longtable."""
    lines: list[str] = [
        "% Auto-generated by scripts/generate_thesis_numbers.py",
        "% Source: src/asset_universe.ETF_UNIVERSE",
        "% Do not edit by hand.",
        r"\begin{longtable}{p{3.2cm}p{3.0cm}p{4.8cm}}",
        r"\caption{ETF 资产池}\label{tab:etf_pool}\\",
        r"\toprule",
        r"ETF & Ticker & 资产类别 \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"ETF & Ticker & 资产类别 \\",
        r"\midrule",
        r"\endhead",
    ]

    current_section: str | None = None
    for etf in ETF_UNIVERSE:
        section = _etf_section(etf)
        if section != current_section:
            current_section = section
            lines.append(f"% {section}")
        lines.append(f"{etf.new_name} & {etf.ticker} & {section} \\\\")

    lines += [
        r"\bottomrule",
        r"\end{longtable}",
        "",
    ]
    out_path = out_dir / "generated_etf_pool_table.tex"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("wrote ETF pool table -> %s (%d ETFs)", out_path, len(ETF_UNIVERSE))


def _asset_stats_table(stats_df: pd.DataFrame, out_dir: Path) -> None:
    """Write one combined ETF identity, category, and performance longtable."""
    # Ticker is the stable join key when a public display name is corrected.
    indexed = stats_df.set_index("ticker")

    lines: list[str] = [
        "% Auto-generated by scripts/generate_thesis_numbers.py",
        "% Sources: src/asset_universe.ETF_UNIVERSE and",
        "%          results/tables/asset_descriptive_statistics.csv",
        "% Do not edit by hand.",
        r"{\scriptsize",
        r"\setlength{\tabcolsep}{2.8pt}",
        r"\renewcommand{\arraystretch}{1.12}",
        r"\begin{longtable}{@{}p{2.15cm}p{1.55cm}p{1.80cm}rrrr@{}}",
        r"\caption{ETF 资产类型与历史表现}\label{tab:asset_stats}\\",
        r"\toprule",
        r"ETF & 代码 & 类别 & 样本数 & 年化收益 & 年化波动 & 最大回撤 \\",
        r"\midrule",
        r"\endfirsthead",
        r"\toprule",
        r"ETF & 代码 & 类别 & 样本数 & 年化收益 & 年化波动 & 最大回撤 \\",
        r"\midrule",
        r"\endhead",
    ]

    current_section: str | None = None
    has_short_history = False
    for etf in ETF_UNIVERSE:
        section = _etf_section(etf)
        if section != current_section:
            current_section = section
            lines.append(f"% {section}")

        name = etf.new_name
        if etf.ticker not in indexed.index:
            logger.warning("ETF %s (%s) missing from stats CSV; skipping", name, etf.ticker)
            continue

        row = indexed.loc[etf.ticker]
        obs = int(row["available_observations"])
        ret = _pct(float(row["annualized_return"]))
        vol = _pct(float(row["annualized_volatility"]))
        mdd = _pct(float(row["max_drawdown"]))

        if obs < _SHORT_HISTORY_OBS:
            obs_str = f"{obs}$^*$"
            has_short_history = True
        else:
            obs_str = str(obs)

        lines.append(
            f"{name} & {etf.ticker} & {section} & {obs_str} & "
            f"{ret} & {vol} & {mdd} \\\\"
        )

    lines.append(r"\bottomrule")
    if has_short_history:
        lines.append(
            r"\multicolumn{7}{@{}l}{\footnotesize $^*$ 近期上市 ETF，"
            r"可用历史较短，仅在积累足够观测后参与优化。} \\"
        )
    lines += [r"\end{longtable}", r"}", ""]

    out_path = out_dir / "generated_asset_stats_table.tex"
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info("wrote asset stats table -> %s", out_path)


def _rebalance_frequency_table(freq_df: pd.DataFrame, out_dir: Path) -> None:
    """Write generated_rebalance_frequency_table.tex from the frequency CSV."""
    indexed = freq_df.set_index("frequency_code")
    rows: list[str] = []
    for code, (_, cn_label) in FREQUENCY_SLUGS.items():
        if code not in indexed.index:
            logger.warning("frequency %s missing from rebalance sensitivity CSV; skipping", code)
            continue
        row = indexed.loc[code]
        rows.append(
            f"{cn_label} & {int(row['rebalance_count'])} & "
            f"{_pct(float(row['net_annual_return']))} & "
            f"{_num(float(row['sharpe_ratio']))} & "
            f"{_pct(float(row['max_drawdown']))} & "
            f"{_pct(float(row['avg_monthly_turnover']))} & "
            f"{_pct(float(row['solver_fallback_rate']))} \\\\"
        )

    lines = [
        "% Auto-generated by scripts/generate_thesis_numbers.py",
        "% Source: results/tables/rebalance_frequency_sensitivity.csv",
        "% Do not edit by hand.",
        r"\begin{table}[H]",
        r"\centering",
        r"\small",
        r"\caption{调仓频率敏感性检验（固定 Improved Convex Adaptive Global RRP 参数）}",
        r"\label{tab:rebalance_frequency_sensitivity}",
        r"\begin{tabular}{lrrrrrr}",
        r"\toprule",
        r"调仓频率 & 调仓次数 & 净年化收益 & Sharpe & 最大回撤 & 月均换手 & 求解器回退率 \\",
        r"\midrule",
        *rows,
        r"\bottomrule",
        r"\multicolumn{7}{l}{\footnotesize 仅改变调仓日历，不重新选择候选参数；月均换手按评价窗口内总换手除以月数计算。} \\",
        r"\end{tabular}",
        r"\end{table}",
        "",
    ]
    out_path = out_dir / "generated_rebalance_frequency_table.tex"
    out_path.write_text("\n".join(lines), encoding="utf-8")
    logger.info("wrote rebalance frequency table -> %s", out_path)


def _asset_stat_macros(stats_df: pd.DataFrame) -> list[str]:
    """Return \\newcommand macros for specific ETF stats cited in prose."""
    indexed = stats_df.set_index("etf")
    lines = ["% --- Per-ETF stat macros for prose (results/tables/asset_descriptive_statistics.csv) ---"]

    # Mapping: (tex_macro_name, etf_name, column, formatter)
    targets: list[tuple[str, str, str, str]] = [
        ("dailEtfVol",        "日利ETF",      "annualized_volatility", "pct"),
        ("goldEtfReturn",     "黄金ETF",       "annualized_return",     "pct"),
        ("goldEtfVol",        "黄金ETF",       "annualized_volatility", "pct"),
        ("silverLofReturn",   "白银LOF",       "annualized_return",     "pct"),
        ("silverLofVol",      "白银LOF",       "annualized_volatility", "pct"),
        ("chuangyeEtfReturn", "创业板ETF",     "annualized_return",     "pct"),
        ("chinaKoreaObs",     "中韩半导体ETF", "available_observations","int"),
        ("chinaKoreaReturn",  "中韩半导体ETF", "annualized_return",     "pct"),
        ("chinaKoreaVol",     "中韩半导体ETF", "annualized_volatility", "pct"),
        ("kcbFiftyObs",       "科创50ETF",     "available_observations","int"),
    ]

    for tex_name, etf_name, col, fmt in targets:
        if etf_name not in indexed.index:
            logger.warning("ETF %s not found in stats_df for macro \\%s", etf_name, tex_name)
            continue
        val = indexed.loc[etf_name, col]
        if fmt == "pct":
            value_str = _pct(float(val))
        elif fmt == "int":
            value_str = str(int(float(val)))
        else:
            value_str = _num(float(val))
        lines.append(f"\\newcommand{{\\{tex_name}}}{{{value_str}}}")

    lines.append("")
    return lines


def _eval_period_macros(first_date: str | None, last_date: str | None) -> list[str]:
    """Return macros for the evaluation period: ETF count, months, tx cost."""
    lines = ["% --- Evaluation-period summary macros ---"]
    lines.append(f"\\newcommand{{\\etfCount}}{{{len(ETF_UNIVERSE)}}}")
    lines.append(f"\\newcommand{{\\evalStartDate}}{{{_EVAL_START_DATE}}}")
    lines.append(f"\\newcommand{{\\evalEndDate}}{{{_EVAL_END_DATE}}}")
    # Compute inclusive month count over the evaluation window.
    try:
        end = datetime.strptime(_EVAL_END_DATE, "%Y-%m-%d")
        start = datetime.strptime(_EVAL_START_DATE, "%Y-%m-%d")
        months = (end.year - start.year) * 12 + end.month - start.month + 1
        lines.append(f"\\newcommand{{\\evalMonths}}{{{months}}}")
    except ValueError:
        pass
    # Rebalancing count: read from actual returns CSV if available, else = evalMonths.
    rebal_path = resolve_path(
        "results/tables/improved_convex_adaptive_global_relaxed_risk_parity_returns.csv"
    )
    if Path(rebal_path).exists():
        try:
            rdf = pd.read_csv(rebal_path, usecols=["date", "is_rebalance_day"])
            rdf["date"] = pd.to_datetime(rdf["date"])
            n_rebal = int(
                ((rdf["date"] >= _EVAL_START_DATE) & (rdf["is_rebalance_day"] == True)).sum()
            )
            lines.append(f"\\newcommand{{\\rebalancingPoints}}{{{n_rebal}}}")
        except Exception as exc:
            logger.warning("could not read rebalancing count: %s", exc)
    lines.append(r"\newcommand{\txCostBps}{3}")
    lines.append("")
    return lines


def _percent_summary_rows(summary: pd.DataFrame) -> list[str]:
    lines: list[str] = []
    indexed = summary.set_index("model")
    for model_name, slug in MODEL_SLUGS.items():
        if model_name not in indexed.index:
            logger.warning("model %s missing from summary CSV; skipping", model_name)
            continue
        row = indexed.loc[model_name]
        lines.append(f"% --- {model_name} ---")
        lines.append(f"\\newcommand{{\\{slug}NetReturn}}{{{_pct(row['net_annual_return'])}}}")
        lines.append(f"\\newcommand{{\\{slug}Volatility}}{{{_pct(row['annualized_volatility'])}}}")
        lines.append(f"\\newcommand{{\\{slug}Sharpe}}{{{_num(row['sharpe_ratio'])}}}")
        lines.append(f"\\newcommand{{\\{slug}Sortino}}{{{_num(row['sortino_ratio'])}}}")
        lines.append(f"\\newcommand{{\\{slug}MaxDD}}{{{_pct(row['max_drawdown'])}}}")
        lines.append(f"\\newcommand{{\\{slug}Calmar}}{{{_num(row['calmar_ratio'])}}}")
        if "cvar_95_daily_loss" in row.index:
            lines.append(f"\\newcommand{{\\{slug}Cvar}}{{{_pct(row['cvar_95_daily_loss'])}}}")
        lines.append(
            f"\\newcommand{{\\{slug}MonthlyTurnover}}"
            f"{{{_pct(row['avg_monthly_turnover'])}}}"
        )
        lines.append("")
    return lines


def _rebalance_frequency_rows(freq_df: pd.DataFrame) -> list[str]:
    indexed = freq_df.set_index("frequency_code")
    lines = ["% --- Rebalance-frequency sensitivity (results/tables/rebalance_frequency_sensitivity.csv) ---"]
    for code, (slug, _) in FREQUENCY_SLUGS.items():
        if code not in indexed.index:
            continue
        row = indexed.loc[code]
        lines.append(f"\\newcommand{{\\{slug}NetReturn}}{{{_pct(float(row['net_annual_return']))}}}")
        lines.append(f"\\newcommand{{\\{slug}Sharpe}}{{{_num(float(row['sharpe_ratio']))}}}")
        lines.append(f"\\newcommand{{\\{slug}MaxDD}}{{{_pct(float(row['max_drawdown']))}}}")
        lines.append(f"\\newcommand{{\\{slug}MonthlyTurnover}}{{{_pct(float(row['avg_monthly_turnover']))}}}")
        lines.append(f"\\newcommand{{\\{slug}SolverFallback}}{{{_pct(float(row['solver_fallback_rate']))}}}")
        lines.append(f"\\newcommand{{\\{slug}RebalanceCount}}{{{int(row['rebalance_count'])}}}")
    if "M" in indexed.index and "W" in indexed.index:
        monthly = indexed.loc["M"]
        weekly = indexed.loc["W"]
        lines.append(
            f"\\newcommand{{\\freqWeeklyMonthlyTurnoverGap}}"
            f"{{{_pct(float(weekly['avg_monthly_turnover']) - float(monthly['avg_monthly_turnover']))}}}"
        )
    lines.append("")
    return lines


def _manifest_dates() -> tuple[str | None, str | None]:
    path = resolve_path("data/MANIFEST.json")
    if not Path(path).exists():
        return None, None
    try:
        data = json.loads(Path(path).read_text(encoding="utf-8"))
    except Exception as exc:
        logger.warning("could not read data manifest: %s", exc)
        return None, None
    return data.get("first_date"), data.get("last_date")


def _walkforward_rows() -> list[str]:
    path = resolve_path("results/tables/walkforward_validation_summary.csv")
    if not Path(path).exists():
        logger.info("walkforward_validation_summary.csv missing — skipping dispersion macros")
        return []
    df = pd.read_csv(path)
    if "metric" in df.columns:
        rows = df.set_index("metric")
    elif "model" in df.columns:
        rows = df.set_index("model")
    else:
        return []
    lines = ["% --- Walk-forward dispersion (results/tables/walkforward_validation_summary.csv) ---"]
    candidates = {
        "sharpe": ("test_sharpe", "validation_sharpe", "sharpe_ratio", "sharpe"),
        "netReturn": ("test_net_annual_return", "validation_net_annual_return", "net_annual_return"),
        "maxDD": ("test_max_drawdown", "validation_max_drawdown", "max_drawdown"),
    }
    # p05/p95 percentile names must avoid digits → use PFive / PNinetyFive
    stat_columns = ("mean", "std", "min", "max", "p05", "p95", "median")
    _stat_tex_name = {
        "mean": "Mean", "std": "Std", "min": "Min", "max": "Max",
        "p05": "PFive", "p95": "PNinetyFive", "median": "Median",
    }
    for tex_key, metric_names in candidates.items():
        target = None
        for name in metric_names:
            if name in rows.index:
                target = name
                break
        if target is None:
            continue
        row = rows.loc[target]
        if hasattr(row, "iloc") and getattr(row, "ndim", 1) > 1:
            row = row.iloc[0]
        for stat in stat_columns:
            if stat not in row.index:
                continue
            value = float(row[stat])
            formatter = _pct if tex_key != "sharpe" else _num
            digits = 2 if formatter is _pct else 3
            stat_tex = _stat_tex_name[stat]
            lines.append(
                f"\\newcommand{{\\walkforward{tex_key.title()}{stat_tex}}}"
                f"{{{formatter(value, digits)}}}"
            )
    lines.append("")
    return lines


def _breakeven_rows() -> list[str]:
    path = resolve_path("results/tables/transaction_cost_breakeven.csv")
    if not Path(path).exists():
        return []
    df = pd.read_csv(path)
    if df.empty:
        return []
    lines = ["% --- Transaction-cost break-even (results/tables/transaction_cost_breakeven.csv) ---"]
    for _, row in df.iterrows():
        slug = str(row.get("slug", "")).strip()
        if not slug:
            continue
        if "breakeven_bps" in row.index:
            if pd.notna(row["breakeven_bps"]):
                lines.append(
                    f"\\newcommand{{\\costBreakeven{slug}}}{{{_num(float(row['breakeven_bps']), 2)} bps}}"
                )
            else:
                max_tested = str(row.get("cost_levels_tested_bps", "50")).split(",")[-1].strip()
                lines.append(
                    f"\\newcommand{{\\costBreakeven{slug}}}{{>{max_tested} bps}}"
                )
    lines.append("")
    return lines


def _vol_aligned_rows() -> list[str]:
    path = resolve_path("results/tables/vol_aligned_comparison.csv")
    if not Path(path).exists():
        return []
    df = pd.read_csv(path)
    if df.empty:
        return []
    lines = ["% --- Vol-aligned HRP comparison (results/tables/vol_aligned_comparison.csv) ---"]
    for _, row in df.iterrows():
        slug = str(row.get("slug", "")).strip()
        if not slug:
            continue
        if "net_annual_return" in row.index:
            lines.append(
                f"\\newcommand{{\\{slug}NetReturn}}{{{_pct(float(row['net_annual_return']))}}}"
            )
        if "sharpe_ratio" in row.index:
            lines.append(
                f"\\newcommand{{\\{slug}Sharpe}}{{{_num(float(row['sharpe_ratio']))}}}"
            )
        if "annualized_volatility" in row.index:
            lines.append(
                f"\\newcommand{{\\{slug}Volatility}}{{{_pct(float(row['annualized_volatility']))}}}"
            )
    lines.append("")
    return lines


def _sharpe_diff_rows() -> list[str]:
    path = resolve_path("results/tables/sharpe_difference_tests.csv")
    if not Path(path).exists():
        logger.info("sharpe_difference_tests.csv missing — skipping diff macros")
        return []
    df = pd.read_csv(path)
    lines = ["% --- Sharpe-difference tests (results/tables/sharpe_difference_tests.csv) ---"]
    for _, row in df.iterrows():
        key = (str(row["model_a"]), str(row["model_b"]))
        slug = DIFF_SLUGS.get(key)
        if slug is None:
            continue
        lines.append(f"\\newcommand{{\\{slug}Diff}}{{{_num(row['observed_difference'])}}}")
        lines.append(f"\\newcommand{{\\{slug}CILow}}{{{_num(row['ci_low'])}}}")
        lines.append(f"\\newcommand{{\\{slug}CIHigh}}{{{_num(row['ci_high'])}}}")
        lines.append(f"\\newcommand{{\\{slug}PValue}}{{{_num(row['p_value_two_sided'])}}}")
        lines.append(
            f"\\newcommand{{\\{slug}Significant}}"
            f"{{{('显著' if bool(row['significant_at_95pct']) else '不显著')}}}"
        )
        lines.append("")
    return lines


def _latest_diagnostic_rows() -> list[str]:
    """Generate thesis macros from current robustness and attribution CSVs."""
    lines = ["% --- Current robustness and attribution diagnostics ---"]

    sub = pd.read_csv(resolve_path("results/tables/robustness_subperiod_summary.csv"))
    improved = sub[
        sub["model"].isin([
            "Improved Convex Adaptive Global RRP",
            "Improved Convex Adaptive Global Relaxed Risk Parity",
        ])
        & sub["window"].isin(["full_available_sample", "pre_2020", "2020_2021", "post_2021", "post_2022"])
    ]
    global_rrp = sub[
        sub["model"].isin(["Global RRP", "Global Relaxed Risk Parity"])
        & sub["window"].eq("post_2021")
    ]
    if improved.empty or global_rrp.empty:
        raise ValueError("Current fixed subperiod diagnostics are incomplete.")
    weak = improved.loc[improved["sharpe_ratio"].idxmin()]
    improved_post = improved[improved["window"].eq("post_2021")].iloc[0]
    weakest_window = str(weak["window"]).replace("_", r"\_")
    lines.extend([
        f"\\newcommand{{\\subperiodImprovedSharpeMin}}{{{_num(improved['sharpe_ratio'].min())}}}",
        f"\\newcommand{{\\subperiodImprovedSharpeMax}}{{{_num(improved['sharpe_ratio'].max())}}}",
        f"\\newcommand{{\\subperiodImprovedSharpeMean}}{{{_num(improved['sharpe_ratio'].mean())}}}",
        f"\\newcommand{{\\subperiodImprovedWeakestWindow}}{{{weakest_window}}}",
        f"\\newcommand{{\\subperiodImprovedWeakestSharpe}}{{{_num(float(weak['sharpe_ratio']))}}}",
        f"\\newcommand{{\\subperiodGlobalPostSharpe}}{{{_num(float(global_rrp.iloc[0]['sharpe_ratio']))}}}",
        f"\\newcommand{{\\subperiodImprovedPostSharpe}}{{{_num(float(improved_post['sharpe_ratio']))}}}",
    ])

    factors = pd.read_csv(resolve_path("results/tables/asset_pricing_factor_exposure_summary.csv"))
    for labels, slug in [
        (["Global RRP", "Global Relaxed Risk Parity"], "Global"),
        (["Improved Convex Adaptive Global RRP", "Improved Convex Adaptive Global Relaxed Risk Parity"], "Improved"),
    ]:
        row = factors[factors["model"].isin(labels)].iloc[0]
        values = {
            "EquityExposure": _num(float(row["avg_exposure_equity"])),
            "BondExposure": _num(float(row["avg_exposure_bond"])),
            "CommodityExposure": _num(float(row["avg_exposure_commodity_gold"])),
            "DefensiveExposure": _num(float(row["avg_exposure_defensive"])),
            "MaxExposure": _num(float(row["max_asset_class_exposure"])),
            "RSquared": _num(float(row["r_squared"])),
            "Alpha": _pct(float(row["alpha_annualized"])),
            "AlphaTstat": _num(float(row["alpha_tstat"]), 2),
        }
        lines.extend(f"\\newcommand{{\\factor{slug}{name}}}{{{value}}}" for name, value in values.items())

    return_attr = pd.read_csv(resolve_path("results/tables/asset_pricing_return_attribution.csv"))
    risk_attr = pd.read_csv(resolve_path("results/tables/asset_pricing_risk_attribution.csv"))
    labels = ["Improved Convex Adaptive Global RRP", "Improved Convex Adaptive Global Relaxed Risk Parity"]
    ret = return_attr[return_attr["model"].isin(labels)].set_index("asset_class")
    risk = risk_attr[risk_attr["model"].isin(labels)].set_index("asset_class")
    class_slugs = {"equity": "Equity", "bond": "Bond", "commodity_gold": "Commodity", "defensive": "Defensive"}
    for asset_class, slug in class_slugs.items():
        lines.append(f"\\newcommand{{\\attr{slug}ReturnShare}}{{{_pct(float(ret.loc[asset_class, 'share_of_average_portfolio_return']), 1)}}}")
        lines.append(f"\\newcommand{{\\attr{slug}RiskShare}}{{{_pct(float(risk.loc[asset_class, 'variance_share_approx']), 1)}}}")
    residual = 1.0 - float(ret["share_of_average_portfolio_return"].sum())
    lines.append(f"\\newcommand{{\\attrResidualReturnShare}}{{{_pct(residual, 1)}}}")

    bootstrap = pd.read_csv(resolve_path("results/tables/robustness_block_bootstrap_summary.csv"))
    bootstrap_models = [
        (["Global RRP", "Global Relaxed Risk Parity"], "BootstrapGlobal"),
        (["Convex Adaptive Global RRP", "Convex Adaptive Global Relaxed Risk Parity"], "BootstrapConvex"),
        (["Improved Convex Adaptive Global RRP", "Improved Convex Adaptive Global Relaxed Risk Parity"], "BootstrapImproved"),
    ]
    for labels, slug in bootstrap_models:
        row = bootstrap[bootstrap["model"].isin(labels)].iloc[0]
        lines.extend([
            f"\\newcommand{{\\{slug}SharpeMean}}{{{_num(float(row['bootstrap_sharpe_mean']))}}}",
            f"\\newcommand{{\\{slug}SharpePFive}}{{{_num(float(row['bootstrap_sharpe_p05']))}}}",
            f"\\newcommand{{\\{slug}SharpePFifty}}{{{_num(float(row['bootstrap_sharpe_p50']))}}}",
            f"\\newcommand{{\\{slug}SharpePNinetyFive}}{{{_num(float(row['bootstrap_sharpe_p95']))}}}",
            f"\\newcommand{{\\{slug}MDDMean}}{{{_pct(float(row['bootstrap_max_drawdown_mean']))}}}",
            f"\\newcommand{{\\{slug}MDDPFive}}{{{_pct(float(row['bootstrap_max_drawdown_p05']))}}}",
        ])

    regime = pd.read_csv(resolve_path("results/tables/regime_oos_validation.csv"))
    regime = regime[regime["holdout"].eq("oos_2024")].set_index("arm")
    for arm, slug in [("baseline_ewma", "RegimeBaseline"), ("regime_selected", "RegimeSelected")]:
        row = regime.loc[arm]
        lines.extend([
            f"\\newcommand{{\\{slug}Sharpe}}{{{_num(float(row['sharpe']))}}}",
            f"\\newcommand{{\\{slug}MaxDD}}{{{_pct(float(row['max_drawdown']))}}}",
            f"\\newcommand{{\\{slug}NetReturn}}{{{_pct(float(row['net_annual_return']))}}}",
            f"\\newcommand{{\\{slug}Cvar}}{{{_pct(float(row['cvar']), 3)}}}",
        ])
    lines.append("")
    return lines


_FALLBACK_MACROS: list[str] = [
    # Per-ETF stat macros
    "dailEtfVol", "goldEtfReturn", "goldEtfVol", "silverLofReturn", "silverLofVol",
    "chuangyeEtfReturn", "chinaKoreaObs", "chinaKoreaReturn", "chinaKoreaVol", "kcbFiftyObs",
    # Walk-forward dispersion
    "walkforwardSharpeMean", "walkforwardSharpeStd", "walkforwardSharpeMin",
    "walkforwardSharpeMax", "walkforwardSharpeMedian",
    "walkforwardNetreturnMean", "walkforwardNetreturnStd", "walkforwardNetreturnMin",
    "walkforwardNetreturnMax", "walkforwardNetreturnPFive", "walkforwardNetreturnPNinetyFive",
    "walkforwardMaxddMean",
    # Transaction-cost break-even
    "costBreakevenImprovedVsGlobal", "costBreakevenGlobalVsEqual", "costBreakevenDefensiveVsEqual",
    # Rebalance-frequency sensitivity
    "freqWeeklyNetReturn", "freqWeeklySharpe", "freqWeeklyMaxDD", "freqWeeklyMonthlyTurnover",
    "freqWeeklySolverFallback", "freqWeeklyRebalanceCount",
    "freqBiweeklyNetReturn", "freqBiweeklySharpe", "freqBiweeklyMaxDD", "freqBiweeklyMonthlyTurnover",
    "freqBiweeklySolverFallback", "freqBiweeklyRebalanceCount",
    "freqMonthlyNetReturn", "freqMonthlySharpe", "freqMonthlyMaxDD", "freqMonthlyMonthlyTurnover",
    "freqMonthlySolverFallback", "freqMonthlyRebalanceCount",
    "freqQuarterlyNetReturn", "freqQuarterlySharpe", "freqQuarterlyMaxDD", "freqQuarterlyMonthlyTurnover",
    "freqQuarterlySolverFallback", "freqQuarterlyRebalanceCount",
    "freqWeeklyMonthlyTurnoverGap",
    # Vol-aligned
    "improvedVolAlignedHrpNetReturn", "improvedVolAlignedHrpSharpe", "improvedVolAlignedHrpVolatility",
    # Sharpe-difference tests
    "improvedVsGlobalDiff", "improvedVsGlobalCILow", "improvedVsGlobalCIHigh",
    "improvedVsGlobalPValue", "improvedVsGlobalSignificant",
    "improvedVsDefensiveDiff", "improvedVsDefensiveCILow", "improvedVsDefensiveCIHigh",
    "improvedVsDefensivePValue", "improvedVsDefensiveSignificant",
    "improvedVsEqualDiff", "improvedVsEqualCILow", "improvedVsEqualCIHigh",
    "improvedVsEqualPValue", "improvedVsEqualSignificant",
    "globalVsEqualDiff", "globalVsEqualCILow", "globalVsEqualCIHigh",
    "globalVsEqualPValue", "globalVsEqualSignificant",
    "defensiveVsEqualDiff", "defensiveVsEqualCILow", "defensiveVsEqualCIHigh",
    "defensiveVsEqualPValue", "defensiveVsEqualSignificant",
]


def _write_fallback(out_dir: Path) -> None:
    """Write generated_fallback.tex with \\providecommand for all optional macros."""
    lines = [
        "% Auto-generated fallback definitions. Do not edit by hand.",
        "% Placeholder values compile the thesis before all pipeline outputs exist.",
        "",
    ]
    for name in _FALLBACK_MACROS:
        lines.append(f"\\providecommand{{\\{name}}}{{?}}")
    lines.append("")
    out_path = out_dir / "generated_fallback.tex"
    # Use Unix line endings to avoid LaTeX CR+LF parsing issues.
    out_path.write_bytes(("\n".join(lines) + "\n").encode("utf-8"))
    logger.info("wrote fallback definitions -> %s", out_path)


def main() -> None:
    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s %(message)s")
    summary_path = resolve_path("results/tables/convex_adaptive_performance_summary.csv")
    if not Path(summary_path).exists():
        raise FileNotFoundError(
            f"performance summary not found at {summary_path}; run scripts/run_convex_adaptive_rrp.py first"
        )
    summary = pd.read_csv(summary_path)

    stats_path = resolve_path("results/tables/asset_descriptive_statistics.csv")
    if not Path(stats_path).exists():
        raise FileNotFoundError(
            f"asset stats not found at {stats_path}; run the full pipeline first"
        )
    stats_df = pd.read_csv(stats_path)

    freq_path = resolve_path("results/tables/rebalance_frequency_sensitivity.csv")
    if not Path(freq_path).exists():
        raise FileNotFoundError(
            f"rebalance frequency sensitivity not found at {freq_path}; "
            "run scripts/run_rebalance_frequency_sensitivity.py first"
        )
    freq_df = pd.read_csv(freq_path)

    first_date, last_date = _manifest_dates()
    out_dir = Path(resolve_path("report/thesis_latex"))
    out_dir.mkdir(parents=True, exist_ok=True)

    # Write the standalone table .tex files and fallback definitions.
    _etf_pool_table(out_dir)
    _asset_stats_table(stats_df, out_dir)
    _rebalance_frequency_table(freq_df, out_dir)
    _write_fallback(out_dir)

    header = [
        "% ===========================================================",
        "%  Auto-generated by scripts/generate_thesis_numbers.py",
        f"%  Generated at (UTC):     {datetime.now(tz=timezone.utc).isoformat()}",
        "%  Sources:",
        "%    - results/tables/convex_adaptive_performance_summary.csv",
        "%    - results/tables/asset_descriptive_statistics.csv",
        "%    - results/tables/rebalance_frequency_sensitivity.csv",
        "%    - results/tables/sharpe_difference_tests.csv (optional)",
        "%    - data/MANIFEST.json (optional, for evaluation dates)",
        "%  Do not edit by hand. Run the generator script after every",
        "%  pipeline rerun to keep thesis numbers in sync with the CSVs.",
        "% ===========================================================",
        "",
    ]
    if first_date is not None:
        header.append(f"\\newcommand{{\\dataFirstDate}}{{{first_date}}}")
    if last_date is not None:
        header.append(f"\\newcommand{{\\dataLastDate}}{{{last_date}}}")
    monthly_rf = load_monthly_risk_free()
    effective = monthly_rf[
        monthly_rf["effective_month"].between(
            pd.Timestamp(_EVAL_START_DATE).to_period("M"),
            pd.Timestamp(_EVAL_END_DATE).to_period("M"),
        )
    ]
    if effective.empty:
        raise ValueError("No monthly risk-free rates cover the evaluation period.")
    header.append(f"\\newcommand{{\\riskFreeRate}}{{{_pct(float(effective['annual_yield'].mean()))}}}")
    header.append(f"\\newcommand{{\\riskFreeRateMin}}{{{_pct(float(effective['annual_yield'].min()))}}}")
    header.append(f"\\newcommand{{\\riskFreeRateMax}}{{{_pct(float(effective['annual_yield'].max()))}}}")
    header.append("")

    content = (
        header
        + _eval_period_macros(first_date, last_date)
        + _percent_summary_rows(summary)
        + _rebalance_frequency_rows(freq_df)
        + _asset_stat_macros(stats_df)
        + _walkforward_rows()
        + _breakeven_rows()
        + _vol_aligned_rows()
        + _sharpe_diff_rows()
        + _latest_diagnostic_rows()
    )
    out_path = out_dir / "generated_numbers.tex"
    out_path.write_text("\n".join(content) + "\n", encoding="utf-8")
    logger.info("wrote %d lines -> %s", len(content), out_path)


if __name__ == "__main__":
    main()
